/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.poo.pkgfinal;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

public class InterfazOpciones extends javax.swing.JFrame {

    private AlmacenLogin aUsuario = new AlmacenLogin();
    private AlmacenProblemas aProblemas = new AlmacenProblemas();
    private int indice;

    /**
     * Creates new form InterfazOpciones
     */
    public InterfazOpciones(AlmacenLogin a, AlmacenProblemas p, int i) {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        aUsuario = a;
        aProblemas = p;
        indice = i;
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("iconocaballo.jpg"));
        this.getContentPane().setBackground(new Color(144, 164, 174));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jugar = new javax.swing.JButton();
        personales = new javax.swing.JButton();
        problemas = new javax.swing.JButton();
        clasificacion = new javax.swing.JButton();
        subir = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Selecciona una opción:");

        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        personales.setText("Estadisticas Personales");
        personales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalesActionPerformed(evt);
            }
        });

        problemas.setText("Estadisticas Problemas");
        problemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemasActionPerformed(evt);
            }
        });

        clasificacion.setText("Clasificación");
        clasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacionActionPerformed(evt);
            }
        });

        subir.setText("Subir Problema");
        subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirActionPerformed(evt);
            }
        });

        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CerrarSesion)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addComponent(personales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(problemas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clasificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jugar)
                .addGap(18, 18, 18)
                .addComponent(personales)
                .addGap(18, 18, 18)
                .addComponent(problemas)
                .addGap(18, 18, 18)
                .addComponent(clasificacion)
                .addGap(18, 18, 18)
                .addComponent(subir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(CerrarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        try {
            int valorDado = ThreadLocalRandom.current().nextInt(0, aProblemas.getProblemas().size());
            new InterfazTablero(aUsuario, aProblemas, indice, valorDado).setVisible(true);
        } catch (MiExcepcion ex) {
            Logger.getLogger(InterfazOpciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);

    }//GEN-LAST:event_jugarActionPerformed

    private void personalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalesActionPerformed
        new InterfazPersonales(aUsuario, aProblemas, indice).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_personalesActionPerformed

    private void subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirActionPerformed
        JFileChooser archivos = new JFileChooser();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("iconocaballo.jpg"));
        FileFilter filtro = new FileNameExtensionFilter("Archivos text (.txt)", "txt");
        archivos.setFileFilter(filtro);
        int status = archivos.showOpenDialog(null);
        if (status == archivos.APPROVE_OPTION) {
            String ruta = archivos.getSelectedFile().getAbsolutePath();
            try {
                aProblemas.subirProblema(ruta);
            } catch (MiExcepcion ex) {
                Logger.getLogger(InterfazOpciones.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (status == archivos.CANCEL_OPTION) {
            archivos.setVisible(false);
        }
    }//GEN-LAST:event_subirActionPerformed

    private void clasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacionActionPerformed
        new InterfazClasificacion(aUsuario, aProblemas, indice).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_clasificacionActionPerformed

    private void problemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemasActionPerformed
        new InterfazEstadisticas(aUsuario, aProblemas, indice).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_problemasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        aProblemas.hacerBackUp();
        aUsuario.hacerBackUp();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        new InterfazLogin(aUsuario, aProblemas).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton clasificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jugar;
    private javax.swing.JButton personales;
    private javax.swing.JButton problemas;
    private javax.swing.JButton subir;
    // End of variables declaration//GEN-END:variables
}
