/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.poo.pkgfinal;

import java.awt.Color;
import java.awt.Toolkit;

public class InterfazClasificacion extends javax.swing.JFrame {

    private AlmacenLogin aUsuario = new AlmacenLogin();
    private AlmacenProblemas aProblemas = new AlmacenProblemas();
    private int indice;

    /**
     * Creates new form InterfazClasificacion
     */
    public InterfazClasificacion(AlmacenLogin a, AlmacenProblemas p, int i) {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        aUsuario = a;
        aProblemas = p;
        indice = i;
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("iconocaballo.jpg"));
        this.getContentPane().setBackground(new Color(144, 164, 174));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResueltosBoton = new javax.swing.JButton();
        PorcentajeBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ResueltosBoton.setText("Resueltos");
        ResueltosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResueltosBotonActionPerformed(evt);
            }
        });

        PorcentajeBoton.setText("Porcentaje");
        PorcentajeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcentajeBotonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, " ", null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Intentos", "Resueltos", "Errores", "%exito"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(ResueltosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PorcentajeBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Volver)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResueltosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PorcentajeBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Volver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResueltosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResueltosBotonActionPerformed
        Clasificacion resueltos = new Clasificacion(aUsuario.getUsuarios());
        resueltos.ordenadaResueltos2();
        mostrar(resueltos);
    }//GEN-LAST:event_ResueltosBotonActionPerformed

    private void PorcentajeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeBotonActionPerformed
        Clasificacion porResueltos = new Clasificacion(aUsuario.getUsuarios());
        porResueltos.ordenadaPorcentaje2();
        mostrar(porResueltos);
    }//GEN-LAST:event_PorcentajeBotonActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        new InterfazOpciones(aUsuario, aProblemas, indice).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        aProblemas.hacerBackUp();
        aUsuario.hacerBackUp();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public void mostrar(Clasificacion resueltos) {
        String matris[][] = new String[resueltos.getCopia().size()][5];

        for (int i = 0; i < resueltos.getCopia().size(); i++) {
            matris[i][0] = resueltos.getCopia().get(i).getLogin();
            matris[i][1] = String.valueOf(resueltos.getCopia().get(i).getProblemas_intentados());
            matris[i][2] = String.valueOf(resueltos.getCopia().get(i).getResueltos());
            matris[i][3] = String.valueOf(resueltos.getCopia().get(i).getErrores());
            matris[i][4] = String.valueOf(resueltos.getCopia().get(i).getPorcentaje_exito());

        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                matris,
                new String[]{
                    "Nombre", "Intentos", "Resueltos", "Errores", "%exito"
                }
        ));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PorcentajeBoton;
    private javax.swing.JButton ResueltosBoton;
    private javax.swing.JButton Volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
